name: pegasus_app
description: "Pegasus - Smart Workflow & Productivity Manager"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  provider: ^6.1.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  connectivity_plus: ^5.0.2

  # UI / UX
  google_fonts: ^6.1.0
  sizer: ^2.0.15
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  share_plus: ^7.2.2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  retrofit_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
